apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-inventario
  labels:
    app: front-inventario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-inventario
  template:
    metadata:
      labels:
        app: front-inventario
    spec:
      containers:
        - name: front-inventario
          image: southamerica-east1-docker.pkg.dev/construtem/microservicios-construtem/front-inventario:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
