apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-ventas
  labels:
    app: front-ventas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-ventas
  template:
    metadata:
      labels:
        app: front-ventas
    spec:
      containers:
        - name: front-ventas
          image: southamerica-east1-docker.pkg.dev/construtem/microservicios-construtem/front-ventas:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
