apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-inventario
  labels:
    app: frontend-inventario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-inventario
  template:
    metadata:
      labels:
        app: frontend-inventario
    spec:
      containers:
        - name: frontend-inventario
          image: southamerica-east1-docker.pkg.dev/construtem/microservicios-construtem/frontend-inventario:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

