apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-inventario-ingress
  annotations:
    kubernetes.io/ingress.class: "gce" # GKE Autopilot usa este controlador por defecto
    networking.gke.io/managed-certificates: "frontend-inventario-cert" # opcional si vas a usar certificado SSL de GKE
spec:
  rules:
    - host: tssw.cl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-inventario-service
                port:
                  number: 80
