apiVersion: v1
kind: Service
metadata:
  name: front-inventario
spec:
  type: NodePort
  selector:
    app: front-inventario
  ports:
    - name: http
      port: 80             # Puerto interno del service
      targetPort: 3000     # Puerto del contenedor
      nodePort: 30080      # Puerto expuesto en el nodo
