apiVersion: v1
kind: Service
metadata:
  name: frontend-inventario-service
spec:
  selector:
    app: frontend-inventario
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
