apiVersion: v1
kind: Service
metadata:
  name: front-inventario-service
  labels:
    app: front-inventario
spec:
  type: ClusterIP
  selector:
    app: front-inventario
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
