apiVersion: v1
kind: Service
metadata:
  name: front-inventario
spec:
  type: LoadBalancer
  selector:
    app: front-inventario
  ports:
    - name: http
      port: 80
      targetPort: 3000
