apiVersion: v1
kind: Service
metadata:
  name: front-ventas-service
  labels:
    app: front-ventas
spec:
  type: ClusterIP
  selector:
    app: front-ventas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
