apiVersion: v1
kind: Service
metadata:
  name: front-inventario
spec:
  type: LoadBalancer
  selector:
    app: front-inventario
  ports:
    - protocol: TCP
      port: 80          # Puerto externo (para acceder desde navegador)
      targetPort: 3000     # Puerto expuesto en el nodo
