apiVersion: v1
kind: Service
metadata:
  name: front-inventario-service
spec:
  type: ClusterIP
  selector:
    app: front-inventario
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
